language: python
python:
  - "3.5"

# command to install dependencies
install:
  - pip install -e .
  - pip install coverage codecov

# command to run tests
script:
  - coverage run -m pytest
  - coverage report

# Push the results back to codecov
after_success:
  - codecov
